---

- name: Arista-Ansible Exercise2
  hosts: pynet-sw1

  tasks:
    - name: Setting Ethernet3 description
      eos_interface: name=Ethernet3 description="*** IN USE 2 ***"
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https

    - name: Set Ethernet3 to access mode, VLAN222
      eos_switchport: name=Ethernet3 mode=access access_vlan=222
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https
